[DEFAULT]
# Keywords to search
keywords = ['AI', 'LLM', 'genAI', 'Artificial Intelligence', 'ChatGPT']
# total amount of posts to get for each keyword ('None' = will collect all possibe for date range)
limit = None
# sorting of posts ('top' or 'latest')
sort = 'top'
# [NOT FINISHED] if posts must be collected over random dates in range ('none' for not OR 'random' for over overall timeline OR 'month' for random set for each month)
#random = random
# if feedback in terminal is wanted ('true' or 'false')
verbose = true
# relative path (using .py file's root folder) for output jsonl files to be placed in (example places in subfolder Scraper_Out)
output_path = Scraper_Out
# date range within which posts must be collected (iso-8601 extended format)
since_date = 2024-07-31T00:00:00Z
until_date = 2025-07-31T00:00:00Z

[LOGIN]
#login details that scraper will use
username = user.bsky.social
password = password123