[DEFAULT]
# Keywords to search
keywords = ['AI', 'LLM', 'genAI', 'gen AI', 'deepfake', 'Artificial Intelligence', 'ChatGPT', 'Gemini', 'Claude', 'Midjourney', 'Dall-e', 'Copilot', 'Synthesia', 'OpenAI', 'Anthropic', 'Stable Diffusion', 'Palantir']
# amount of posts to get of each keyword (if wanted)
limit = None
# if feedback in terminal is wanted
verbose = true
# relative path .py file's root folder for output jsonl files to be placed in (example places in folder Scraper_Out)
output_path = Scraper_Out
# date range within which posts must be collected (iso-8601 extended format)
since_date = 2024-07-31T01:00:00Z
until_date = 2025-07-31T23:59:59Z

[LOGIN]
#login details that scraper will use
username = user.bsky.social
password = password123