[DEFAULT]
# Keywords to search
keywords = ['AI', 'LLM', 'genAI', 'Artificial Intelligence', 'ChatGPT']
# total amount of posts to get for each keyword (None = will collect all possibe for date range)
limit = None
# if feedback in terminal is wanted
verbose = true
# relative path (using .py file's root folder) for output jsonl files to be placed in (example places in subfolder Scraper_Out)
output_path = Scraper_Out
# date range within which posts must be collected (iso-8601 extended format)
since_date = 2024-07-31T01:00:00Z
until_date = 2025-07-31T23:59:59Z

[LOGIN]
#login details that scraper will use
username = user.bsky.social
password = password123