[DEFAULT]
# path to mallet install
malletpath = C:\\MALLET\\Mallet-202108\\bin\\mallet
# relative path (using .py file's root folder) to jsonl file from scraper
jsonfile = projects/Hons-bsky-Posts-cleaning.jsonl
# path to which the formatted posts must be saved
datafile = bsky_posts_for_mallet.txt
# name used to save all mallet files for a project under
setName = bsky_posts_AI
# the number of topics that will be used in trainig
numTopics = 400
# if feedback in terminal is wanted ('true' or 'false')
verbose = true
# if u want to calc perplexity curve of data set
perplexity = true