[DEFUALT]
# relative path to jsonl file with post data from scraper (cleaned)
post_file = projects/Hons-bsky-Posts-Clean.jsonl
# relative path to jsonl file with post sentiment data
sent_file = projects/bsky-posts-sents.jsonl
# relative path to topic distributions file from mallet (requires .topic_num at end)
topic_file = projects/mallet.topic_distributions.50
# relative path to where output jsonl files will be written
out_path = projects/out
# if feedback in terminal is wanted ('true' or 'false')
verbose = true