[DEFUALT]
# relative path (using .py file's root folder) to input jsonl file
datafile = projects/Hons-bsky-Posts-cleaning.jsonl
# file to where sentiments will be stored
savefile = projects/bsky-posts-sents.jsonl
# if feedback in terminal is wanted ('true' or 'false')
verbose = true